site_name: Nexus NX Archive Library
site_url: https://nexus-mods.github.io/NexusMods.Archives.Nx/

repo_name: Nexus-Mods/NexusMods.Archives.Nx
repo_url: https://github.com/Nexus-Mods/NexusMods.Archives.Nx

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nexus-Mods
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

extra_css:
  - Nexus/Stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: nexus-slate
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Usage: Usage.md
  - Benchmarks: Benchmarks.md
  - API Reference:
      - About: Library/About.md
      - Headers:
          - About: Library/Headers/About.md
          - HeaderParser: Library/Headers/HeaderParser.md
          - StringPool: Library/Headers/StringPool.md
      - File Providers:
          - About: Library/FileProviders/About.md
          - Interfaces: Library/FileProviders/Interfaces.md
          - FileData:
              - ArrayFileData: Library/FileProviders/FileData/ArrayFileData.md
              - MemoryMappedFileData: Library/FileProviders/FileData/MemoryMappedFileData.md
              - RentedArrayFileData: Library/FileProviders/FileData/RentedArrayFileData.md
          - Inputs:
              - FromArrayProvider: Library/FileProviders/Inputs/FromArrayProvider.md
              - FromDirectoryDataProvider: Library/FileProviders/Inputs/FromDirectoryDataProvider.md
              - FromStreamProvider: Library/FileProviders/Inputs/FromStreamProvider.md
          - Outputs:
              - OutputArrayProvider: Library/FileProviders/Outputs/OutputArrayProvider.md
              - OutputFileProvider: Library/FileProviders/Outputs/OutputFileProvider.md
      - Traits:
          - About: Library/Traits/About.md
          - ICanConvertToLittleEndian: Library/Traits/ICanConvertToLittleEndian.md
          - ICanProvideFileData: Library/Traits/ICanProvideFileData.md
          - IHasCompressionPreference: Library/Traits/IHasCompressionPreference.md
          - IHasFileSize: Library/Traits/IHasFileSize.md
          - IHasRelativePath: Library/Traits/IHasRelativePath.md
          - IHasSolidType: Library/Traits/IHasSolidType.md
      - Utilities:
        - ArrayRental: Library/Utilities/ArrayRental.md
        - Compression: Library/Utilities/Compression.md
        - FileFinder: Library/Utilities/FileFinder.md
        - LittleEndianReader: Library/Utilities/LittleEndianReader.md
        - LittleEndianWriter: Library/Utilities/LittleEndianWriter.md

  - Contributing to Library: Contributing.md
  - Format Specification:
      - Overview: Specification/Overview.md
      - Header: Specification/File-Header.md
      - Table of Contents (TOC): Specification/Table-Of-Contents.md
      - Optional Sections:
          - User Data: Specification/User-Data.md
      - Algorithm Implementation: Specification/Implementation-Details.md
  - Contributing To Wiki: Contributing-Locally.md
