name: DeployMkDocs

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/DeployMkDocs.yml"
      - "mkdocs.yml"
      - "./docs/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/DeployMkDocs.yml"
      - "mkdocs.yml"
      - "./docs/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/mkdocs-build-and-deploy.yaml@main